### ISSUE TITLE
Feature Request: Add caching to store-api controllers

### ISSUE THREAD

**Issue by ts-mothership** [elkmod/SwagShopwarePwa#81]
Currently the store-api controllers (src/Pwa/Controller/PageController.php) don't implement a caching system. It would nice if you could support caching to avoid load on Shopware's database.

There are tutorials and references how to do it for store-api controllers, for example: 
- https://developer.shopware.com/docs/guides/plugins/plugins/framework/store-api/add-caching-for-store-api-route
- https://github.com/shopware/core/blob/trunk/Content/Category/SalesChannel/CachedCategoryRoute.php

If you want to test caching with Redis, you can create a new file config/packages/shopware.yaml with content
```
framework:
  cache:
    app: cache.adapter.redis
    default_redis_provider: "redis://127.0.0.1:6379"
```

I can imaging that cache invalidation could be difficult when there is only one central interface. But let me know if you have questions.
